flaskapp/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskapp import db, bcrypt
from flaskapp.models import User
from flaskapp.users.forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm
from flaskapp.users.utils import send_reset_email
from flask import current_app

users = Blueprint('users', __name__)     

@users.route('/register', methods=["GET", "POST"])
def register():  
    if current_user.is_authenticated:
        return redirect(url_for('main.size_input'))
    form = RegistrationForm()
    if form.validate_on_submit( ):
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password, history = '')
        db.session.add(user) 
        db.session.commit() 
        flash(f'Account created for {form.username.data}!', 'success')
        current_app.logger.info('New user registered: %s', form.username.data)
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login(): 
    if current_user.is_authenticated:
        return redirect(url_for('main.size_input'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            current_app.logger.info('User login successful: %s', form.email.data)
            return redirect(next_page) if next_page else redirect(url_for('main.size_input'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
            current_app.logger.warning('Invalid login attempt: %s', form.email.data)
    return render_template('login.html', title='Login', form=form)

@users.route("/logout") 
def logout():
    current_app.logger.info('User %s logged out', current_user.username)
    logout_user()
    return redirect(url_for('users.login'))  


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.size_input'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        current_app.logger.info('Password reset requested for: %s', form.email.data)
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.size_input'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        current_app.logger.warning('Invalid or expired reset token used')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        current_app.logger.warning('User %s has updated password', current_user.email)
        flash('Your password has been updated', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form) 

  

flaskapp/templates/layout.html
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Fair Rent Split - {{ title }}</title>
    {% else %}
        <title>Fair Rent Split</title>
    {% endif %}
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              <a class="nav-item nav-link" href="{{ url_for('main.size_input') }}">Home</a>
            {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>

    <main role="main" class="container">
      <!-- <div class="row"> -->
        <!-- <div class="col-md-8"> -->
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        <!-- </div> -->
      <!-- </div> -->
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flaskapp/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href={{ url_for('users.reset_request') }}>Forgot Password?</a>
            </small>
        </form>
    </div>
{% endblock content %}

flaskapp/templates/matrix_input.html
{% extends "layout.html" %}
{% block content %}


<div class="container">
    <h1 class="text-center display-4">RENT PREFERENCES PER ROOM</h1>
    <form method="post" action="/output">
    <table class="matrix-table">
        <thead>
            <tr>
                <th></th>
                {% for j in range(size) %}
                    <th>Room {{ j+1 }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for i in range(size) %}
                <tr>
                    <th>User {{ i+1 }}</th>
                    {% for j in range(size) %}
                        <td>
                            <input type="number" name="{{ i }}-{{ j }}" class="form-control" step="any" placeholder="User {{ i+1 }}, Room {{ j+1 }}" required>
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="matrix-submit">
        <input type="hidden" name="size" value="{{ size }}">
        <input type="hidden" name="rent" value="{{ rent }}">
        <input type="submit" class="btn btn-primary" value="Submit">
    </div>
    </form>>
</div>

<div class="matrix-instructions">
    <h4>Instructions:</h4>
    <ul>
        <li>User i, Room i represents User i's willingness to pay rent for Room i.</li>
        <li>The sum of all rents for each User should add up to the total Rent.</li>
    </ul>
</div>

{% endblock content %}

flaskapp/templates/matrix_size_input.html
{% extends "layout.html" %}
{% block content %}

<div class="container">
    <div class="text-center">
        <h1 class="display-3">FAIR RENT SPLIT APP</h1>
    </div>
    <form method="post" action="/matrix_input" class="text-center">
        <div class="form-group">
            <input type="number" name="size" class="form-control form-control-lg" placeholder="No of Roommates" required>
        </div>
        <div class="form-group">
            <input type="number" name="rent" class="form-control form-control-lg" placeholder="Total Rent" required>
        </div>
        <br>
        <input type="submit" class="btn btn-primary btn-lg" value="Submit">
    </form>
</div>

<br>
<div class="container">
    {% if history|length == 0 %}
        <h3>Welcome, Start splitting rent "FAIRLY" today</h3>
    {% else %}
        <div class="row">
            {% set count = 0 %}
            {% for hist_list in history %}
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">
                            History {{ loop.index }}
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>Roommate</th>
                                        <th>Room</th>
                                        <th>Rent</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for hist in hist_list %}
                                        {% set info = hist.split(' for rent: ') %}
                                        <tr>
                                            <td>{{ info[0].split(' is alloted to room : ')[0] }}</td>
                                            <td>{{ info[0].split(' is alloted to room : ')[1] }}</td>
                                            <td>{{ info[1] }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {% set count = count + 1 %}
            {% endfor %}
        </div>
    {% endif %}
</div>
{% endblock content %}

flaskapp/templates/output.html
{% extends "layout.html" %}
{% block content %}
    <div class="container text-center">
        <h1 style="font-size: 30px;">Rent of Roommates</h1>
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Roommate</th>
                        <th>Room</th>
                        <th>Rent</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in range(size) %}
                        <tr>
                            <td>Roommate {{ i + 1 }}</td>
                            <td>Room {{ final[i][0] + 1 }}</td>
                            <td>{{ final[i][1] }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

flaskapp/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskapp/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskapp/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}